export DEVICE=0
export IMGSZ=640
export BATCH=32
export WORKERS=8
export SEEDS="1 2 3"
export YOLO11_MODEL=yolo11m.pt
export YOLOV8_MODEL=yolov8n.pt
export YOLOV10_MODEL=yolov10n.pt
export RTDETR_MODEL=rtdetr-l.pt
export EPOCHS_YOLO=200
export EPOCHS_RTDETR=120
export EPOCHS_FASTER_RCNN=120
