seed: 42
class_name: drone

drone_detection_dataset:
  train_val_split:
    train_ratio: 0.9
    val_ratio: 0.1

ard_mav:
  split:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
  frame_index_base: 1

